### ISSUE TITLE
请求中...

### ISSUE THREAD

**Issue by MandaCai** [super6wenzi/chatGPT-wx#2]
折腾了半天终于在微信小程序上发布出来了，但是发送信息一直是请求中，请问是配置还是哪里出问题了吗。在chatgpt网站上使用正常

**Comment by super6wenzi** [comment]
如果是答案回答太长的话会这样

**Comment by MandaCai** [comment]
但是发什么都是请求中，就没正常返回信息过

**Comment by CJYIT** [comment]
源码问题没有发送请求

**Comment by super6wenzi** [comment]
> 但是发什么都是请求中，就没正常返回信息过

那就是你没配置后端地址
